---
title: "arima_notes"
author: "Meghan Bowen"
date: "2/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages}

library(tidyverse)
library(knitr)
library(lubridate)

```


```{r load_data}

channel_vis_year <- read_csv("~/github/BowenShinyApp/Visitation_Data/channel_vis_year.csv") %>% 
  select(Year, RecreationVisitors)

arches_vis_year <- read_csv("~/github/BowenShinyApp/Visitation_data/arches_vis_year.csv")
arches_vis_year <- arches_vis_year[-1,]
colnames(arches_vis_year) <- arches_vis_year[1,]
arches_vis_year <- arches_vis_year[-1,]

#Explore yearly data

plot(channel_vis_year)
ggplot(arches_vis_year, aes(x=Year, y=RecreationVisitors))+
  geom_point()


```

```{r clean_month}
##Need to clean the monthly data and make into tidy format

channel_vis_month <- read_csv("~/github/BowenShinyApp/Visitation_Data/channel_vis_month.csv") %>% 
  select(-Textbox5)
channel_vis_month$Year <- as.factor(channel_vis_month$Year)
channel_vis_month <-as.data.frame(channel_vis_month) #don't know if this is necessary atm

<<<<<<< HEAD
separate <- for (i)
channel_group <- lapply()

summarize(channel_group)

=======
channel_group <- channel_vis_month %>% 
  select(Year, JAN) %>% 
  mutate(month = "January")
>>>>>>> 65f77aa40acd88446f8bd048fe17a241f326bb58


```

<<<<<<< HEAD

How to get this data clean!?!?!
1. separate out by column (one column has year, one column has month [jan/feb/etc])
2. rbind by year to original data frame
3. END RESULT:
Year  Month VisitorCount
1979  Jan   2700
1979  Feb   3121
1979  Mar   4774

etcc.... for every year and monthclass

"split-apply-combine" :: https://nicercode.github.io/guides/repeating-things/
=======

>>>>>>> 65f77aa40acd88446f8bd048fe17a241f326bb58
