---
title: "arima_notes"
author: "Meghan Bowen"
date: "2/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages}

library(tidyverse)
library(knitr)
library(lubridate)
library(tseries)
library(forecast)
library(gridExtra)
```

```{r clean_month}
##Need to clean the monthly data and make into tidy format
arches_vis_month <- read_csv("~/github/BowenShinyApp/Visitation_Data/arches_vis_month.csv") %>%
  mutate(ParkName = "Arches")

badlands_vis_month <- read_csv("~/github/BowenShinyApp/Visitation_Data/badlands_vis_month.csv") %>%
  mutate(ParkName = "Badlands")

channel_vis_month <- read_csv("~/github/BowenShinyApp/Visitation_Data/channel_vis_month.csv") %>%
  mutate(ParkName = "Channel Islands")

glacier_vis_month <- read_csv("~/github/BowenShinyApp/Visitation_Data/glacier_vis_month.csv") %>%
  mutate(ParkName = "Glacier")

gteton_vis_month <- read_csv("~/github/BowenShinyApp/Visitation_Data/gteton_vis_month.csv") %>%
  mutate(ParkName = "Grand Teton")

redwood_vis_month <- read_csv("~/github/BowenShinyApp/Visitation_Data/redwood_vis_month.csv") %>%
  mutate(ParkName = "Redwood")

shenandoah_vis_month <- read_csv("~/github/BowenShinyApp/Visitation_Data/shenandoah_vis_month.csv") %>%
  mutate(ParkName = "Shenandoah")

yellowstone_vis_month <- read_csv("~/github/BowenShinyApp/Visitation_Data/yellowstone_vis_month.csv") %>%
  mutate(ParkName = "Yellowstone")

yosemite_vis_month <- read_csv("~/github/BowenShinyApp/Visitation_Data/yosemite_vis_month.csv") %>%
  mutate(ParkName = "Yosemite")

zion_vis_month <- read_csv("~/github/BowenShinyApp/Visitation_Data/zion_vis_month.csv") %>%
  mutate(ParkName = "Zion")


```

```{r monthly_combine}

all_month <- rbind(arches_vis_month, badlands_vis_month, channel_vis_month, glacier_vis_month, gteton_vis_month, redwood_vis_month, shenandoah_vis_month, yellowstone_vis_month, yosemite_vis_month, zion_vis_month)

all_month_visitation <- write_csv(all_month, "all_month_visitation.csv")

```


```{r separate_tidy}

#read in all data from mother .csv
all_month_visitation <- read_csv("~/github/BowenShinyApp/all_month_visitation.csv")

yellowstone <- all_month_visitation %>% 
  filter(ParkName =="Yellowstone") %>% 
  select(-ParkName)

yellowstone$Year <- as.factor(yellowstone$Year)

gather_up <- gather(yellowstone, key = "Month", value = "VisitorCount", JAN:DEC)
#gather_up <- as.data.frame(gather_up)
gather_up$Month <- as.factor(gather_up$Month)

months <- factor(levels = c("JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"))
gather_up$Month <- fct_relevel(gather_up$Month, months)

gather_yellowstone <- gather_up[order(gather_up$Year),]
gather_yellowstone <- unite(gather_yellowstone,
                            Year_Month, c(Year, Month), remove = T)

```

```{r check_arima_assumptions}
#convert to timeseries data
yellowstone_ts <- ts(gather_yellowstone$VisitorCount, frequency = 12, start = c(1979,1))

#any NA values for visitation?
sum(is.na(gather_yellowstone$VisitorCount))

plot(yellowstone_ts)

#check decomposition
yellowstone_decomp <- decompose(yellowstone_ts)
plot(yellowstone_decomp)

#check ACF
yellowstone_acf <- acf(yellowstone_ts)

```

```{r holt_winters}

## the yellowstone decomposition looks pretty good for Holt-Winters?!

# 1. Run Holt-Winters 

yellowstone_hw <- HoltWinters(yellowstone_ts)

# WHAT DOES THIS ERROR MEAN?!
# optimization difficulties: ERROR: ABNORMAL_TERMINATION_IN_LNSRCH
plot(yellowstone_hw)

# 2. Forecast HW (h = 60 for 60 months, aka 5 years)

yellowstone_hw_forecast <- forecast(yellowstone_hw, h = 60)
plot(yellowstone_hw_forecast)

# 3. Residuals. Not looking super normal, but what ever is really....

hist(yellowstone_hw_forecast$residuals)
qqnorm(yellowstone_hw_forecast$residuals)

```

```{r hw_value_calls}

yellowstone_upper <- yellowstone_hw_forecast$upper
yellowstone_lower <- yellowstone_hw_forecast$lower

yellowstone_average <- yellowstone_hw_forecast$mean
yellowstone_average

```

```{r general_plot_code}

# Convert Holt Winters Predictions into df
yellowstone_hw_df <- data.frame(yellowstone_hw_forecast)
month_seq <- seq(1,60)
yellowstone_hw_plot_df <- data.frame(month_seq, yellowstone_hw_df)


#HW Predictions. PLots the average value ("Point.Forecast")
yellowstone_hw_plot <- ggplot(yellowstone_hw_df, 
                              aes(x=month_seq, y = Point.Forecast)) +
  geom_line()

yellowstone_hw_plot

```


##ARIMA code below. DO NOT USE


```{r arima}
## let's see what an ARIMA looks like

# 1. Find pdq values
yellowstone_pdq <- auto.arima(yellowstone_ts)
yellowstone_pdq

## ARIMA predicted pdq: (1,0,0)(0,1,1)[12] 


# 2. Run ARIMA
yellowstone_arima <- arima(yellowstone_ts, 
                           order = c(1,0,0), 
                           seasonal = list(order = c(0,1,1)))
yellowstone_arima

# 3. Check Residuals. not looking great, but not completely not-normal ??

par(mfrow = c(1,2))
hist(yellowstone_arima$residuals)
qqnorm(yellowstone_arima$residuals)

# 4. Forecast: again let's do 5 years (60 months)

yellowstone_arima_forecast <- forecast(yellowstone_arima, h = 60)
plot(yellowstone_arima_forecast)

```

```{r compare_hw_arima}

par(mfrow=c(2,1))
plot(yellowstone_hw_forecast)
plot(yellowstone_arima_forecast)
```



```{r ggplots_hw_arima}
# Convert Holt Winters Predictions into df
yellowstone_hw_df <- data.frame(yellowstone_hw_forecast)
month_seq <- seq(1,60)
yellowstone_hw_plot_df <- data.frame(month_seq, yellowstone_hw_df)

# Convert ARIMA Predictions int odf
yellowstone_arima_df <- data.frame(yellowstone_arima_forecast)
yellowstone_arima_plot_df <- data.frame(month_seq, yellowstone_arima_df)


# Plot 1: HW Predictions
yellowstone_hw_plot <- ggplot(yellowstone_hw_df, 
                              aes(x=month_seq, y = Point.Forecast)) +
  geom_line()

# Plot 2: ARIMA Predictions
yellowstone_arima_plot <- ggplot(yellowstone_arima_df, 
                              aes(x=month_seq, y = Point.Forecast)) +
  geom_line()


# Now BOTH
gridExtra::grid.arrange(grobs = list(yellowstone_hw_plot, yellowstone_arima_plot))


```