---
title: "historic_trends"
author: "Meghan Bowen"
date: "2/21/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Looking at Historic Trends in National Park Attendance

```{r load_packages}

library(tidyverse)
library(knitr)
library(ggfortify) ##for better luck with the monthly data plots, plots ts objects

```
## Part 1. Yearly Attendance

```{r load_clean_year_data}
# Load in All Data
arches_vis_year <- read_csv("~/github/BowenShinyApp/Visitation_data/arches_vis_year.csv")
badlands_vis_year <- read_csv("~/github/BowenShinyApp/Visitation_data/badlands_vis_year.csv")
channel_vis_year <- read_csv("~/github/BowenShinyApp/Visitation_data/channel_vis_year.csv")
glacier_vis_year <- read_csv("~/github/BowenShinyApp/Visitation_data/glacier_vis_year.csv")
gteton_vis_year <- read_csv("~/github/BowenShinyApp/Visitation_data/gteton_vis_year.csv")
redwood_vis_year <- read_csv("~/github/BowenShinyApp/Visitation_data/redwood_vis_year.csv")
shenandoah_vis_year <- read_csv("~/github/BowenShinyApp/Visitation_data/shenandoah_vis_year.csv")
yellowstone_vis_year <- read_csv("~/github/BowenShinyApp/Visitation_data/yellowstone_vis_year.csv")
yosemite_vis_year <- read_csv("~/github/BowenShinyApp/Visitation_data/yosemite_vis_year.csv")
zion_vis_year <- read_csv("~/github/BowenShinyApp/Visitation_data/zion_vis_year.csv")
```

```{r more_wrangling}
# Clean up each individual DF
# Add in ParkName label and millions of visitors (to make it easier to graph)

arches_vis_year <- arches_vis_year %>% 
  mutate(ParkName = "Arches") %>% 
  mutate(Visitors_Mil = RecreationVisitors/1000000)

badlands_vis_year <- badlands_vis_year %>% 
  mutate(ParkName = "Badlands") %>% 
  mutate(Visitors_Mil = RecreationVisitors/1000000)

channel_vis_year <- channel_vis_year %>% 
  mutate(ParkName = "Channel Islands") %>% 
  mutate(Visitors_Mil = RecreationVisitors/1000000)

glacier_vis_year <- glacier_vis_year %>% 
  mutate(ParkName = "Glacier") %>% 
  mutate(Visitors_Mil = RecreationVisitors/1000000)

gteton_vis_year <- gteton_vis_year %>% 
  mutate(ParkName = "Grand Teton") %>% 
  mutate(Visitors_Mil = RecreationVisitors/1000000)

redwood_vis_year <- redwood_vis_year %>% 
  mutate(ParkName = "Redwood") %>% 
  mutate(Visitors_Mil = RecreationVisitors/1000000)

shenandoah_vis_year <- shenandoah_vis_year %>% 
  mutate(ParkName = "Shenandoah") %>% 
  mutate(Visitors_Mil = RecreationVisitors/1000000)

yellowstone_vis_year <- yellowstone_vis_year %>% 
  mutate(ParkName = "Yellowstone") %>% 
  mutate(Visitors_Mil = RecreationVisitors/1000000)

yosemite_vis_year <- yosemite_vis_year %>% 
  mutate(ParkName = "Yosemite") %>% 
  mutate(Visitors_Mil = RecreationVisitors/1000000)

zion_vis_year <- zion_vis_year %>% 
  mutate(ParkName = "Zion") %>% 
  mutate(Visitors_Mil = RecreationVisitors/1000000)

```

```{r combine_df}

#combine all yearly visitation data into one DF
all_year <- rbind(arches_vis_year, badlands_vis_year, channel_vis_year, glacier_vis_year, gteton_vis_year, redwood_vis_year, shenandoah_vis_year, yellowstone_vis_year, yosemite_vis_year, zion_vis_year)

#export to .csv
all_year_visitation <- write_csv(all_year, "all_year_visitation.csv")

```


```{r plot_year}

#load in all year visits
all_year_visitation <- read_csv("~/github/BowenShinyApp/all_year_visitation.csv")

ggplot(all_year_visitation)+
  geom_point(aes(x=Year, y=Visitors_Mil, 
                 col = ParkName),
             subset(all_year_visitation, ParkName == "Yellowstone")) +
  labs(x= "Year",
       y= "Number of Visitors \n (millions)",
       title = "Yearly Visitors to ",
       subtitle = "(1904-2018)") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        legend.position = "none")

```


## Part 2. Monthly Attendance

```{r load_clean_monthly_data}

# Need to clean like the HW/ARIMA data

yellowstone_vis_month <- read_csv("~/github/BowenShinyApp/Visitation_Data/yellowstone_vis_month.csv") %>%
  select(-Textbox5)
yellowstone_vis_month$Year <- as.factor(yellowstone_vis_month$Year)

gather_up <- gather(yellowstone_vis_month, key = "Month", value = "VisitorCount", JAN:DEC)

gather_up$Month <- as.factor(gather_up$Month)
gather_up$Month <- fct_relevel(gather_up$Month, "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC")

gather_yellowstone <- gather_up[order(gather_up$Year),] %>% 
  mutate(Visitors_Thou = VisitorCount/1000)

# change to ts object
yellowstone_monthly_ts <- ts(gather_yellowstone$Visitors_Thou, frequency = 12, start = c(1979,1))

```

```{r plot_monthly}

ggplot2::autoplot(yellowstone_monthly_ts) +
  labs(x= "Year",
       y= "Number of Visitors \n (millions)",
       title = "Monthly Visitors to Yellowstone",
       subtitle = "(1979-2018)") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))

```