---
title: "Travel Cost Data Sources"
author: "Meghan Bowen"
date: "3/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(knitr)

```

# Sources for Travel Cost Calculations:


## 1. Park Entrance Fee (per trip): 
(https://www.nps.gov/aboutus/entrance-fee-prices.htm)

- used the per vehicle price -- fees listed "current" or (if applicable) after January 1, 2019





## 2. Campground Fee (per day): 
(https://www.nps.gov/subjects/camping/campground.htm)

- price is reflected in the "individual campground" fee category listed for each park

###Campsites used for fees:
- Arches: used Devils Garden Campground
- Badlands: used Cedar Pass Campground
- Channel Islands: used $15 base rate quoted on their website
- Glacier: used Bartlett Cove Campground, free permit for camping?!
- Grand Teton: 6 campgrounds total, all have different opening times and fees. See below for calculations for averge per month
- Redwood: most are free, except for one that charges $5. not including this outlier in the data
- Shenandoah: four campgrounds, see below for calculations. **NOTE that none of the campgrounds are open from Nov-Feb**
- Yellowstone: eleven campgrounds listed on their site (but only 10 are open as of 2019), see below for calculations.
- Yosemite: thirteen campgrounds, see below for calculations
- Zion: using the three official campgrounds. see below


###Grand Teton Camping Calculations (average price throughout year)

1. Colter Bay: $31 (May-Sept)
2. Gros Ventre: $29 (May-Oct)
3. Headwaters: $37.50 (May-Sept)
4. Jenny Lake: $29 (May-Sept)
5. Signal Mountain: $32 (May-Otct)
6. Lizard Creek: $30 (June-Sept)
7. "Primitive Winter Camping" : $5 (Dec-April)

####Grand Teton Camping Averages ($/day)
Dec-April: $5 
May: $31.70
June-Sept: $31.42
Oct: $30.50
Nov: NA (Cannot camp per the website)

###Shenandoah Camping Calculations (average prices throughout year)
1. Mathews Arm: $15 (May-Oct)
2. Big Meadows: $20 (Mar-midNov)
3. Lewis Mountain: $15 (Mar-Oct?)
4. Loft Mountain: $15 (May-Oct)

####Shenandoah Camping Averages ($/day)
Dec-Feb: NA
Mar-Apr: $17.50
May-Oct: $16.25
Nov*: $20
*data assumes $20 fee for every day in November -- Big Meadows is ony open until mid-November. 

###Yellowstone Camping Calculations (average prices throughout the year)
1. Bridge Bay: $26 (May-Sept)
2. Canyon: $31 (May-Sept)
3. Grant Village: $31 (June-Sept)
4. Madison: $26 (Apr-Oct)
5. Indian Creek: $15 (June-Sept)
6. Lewis Lake: $15 (June-Nov)
7. Mammoth: $20 (ALL YEAR)
8. Norris: $20 (May-Sept)
9. Pebble Creek: $15 (June-Sept)
10. Slough Creek: $15 (June-Oct)
11. Tower Fall: $15(may-sept)

####Yellowstone Camping Averages ($/day)
Dec-Mar: $20 (only one campsite open)
Apr: $23 (two open)
May: $23 (six open)
June-Sept: $20.81 (all open)
Oct: $20.33 (3 open)
Nov: $17.50 (two open)

###Yosemite Camping Calculations (average prices throughout the year)
1. Upper Pines: $26 (ALL YEAR)
2. Lower Pines: $ 26 (April-Oct)
3. North Pines: $26 (Mar-Oct)
4. Camp 4: $12 (for two people, all year)
5. Wawona: $26 (all year)
6. Bridalveil Creek: $18 (Jul-Sept)
7. Hogdon Meadows: $ 26 (Apr-Oct)
8. Crane Flat: $26 (May-Oct)
9. Tamarack Flat: $12 (May-Oct)
10. White Wolf: $18 (June-Sep)
11. Yosemite Creek: $12 (Jul-Oct)
12. Porcupine Flat: $12 (Jul-Oct)
13. Tuolumne Meadows: $26 (Jun-Sept)

####Yosemite Camping Averages ($/day)
Nov-Feb: $21.33 (3 open)
Mar: $22.50 (4 open)
Apr: $23.67 (6 open)
May: $22.50 (8 open)
Jun: $22.40 (10 open)
Jul-Sept: $20.46 (all 13 open)
Oct: $20.40 (10 open)

###Zion Camping Calculations:
1. Lava : $0 free? (May-Sept)
2. South : $20 (Feb-Nov)
3. Watchman: $30 (all year)

####Zion Camping Averages ($/day)
Dec-Jan: $30
Feb-Apr: $25
May-Sept: $16.67
Oct-Nov: $25




## 3. Lodge/Hotel Prices (per day) : 
https://www.nationalparkreservations.com

- used an average price for each month for three local lodges/hotels from the above website
- chose the three lowest price under category lodges/hotels :: trying to save money here!
- price based on one room, 2 people occupancy, rate for 2 nights
- all prices calculated for next year (Jan 2020, etc)
- used lowest listed price for a room
- price does NOT include taxes or other room fees
- NOT including any seasonality in pricing, too much detail and I don't want to collect that fine scale of information

### 1. Arches:
- Aarchway Inn ($80/night)
- Best Western Greenwell ($87/night)
- Best Western Canyonlands ($94/night)

####average price per day (no monthly changes):
80 + 87+ 94/3 = 87


### 2. Badlands (only three listed)
- Best Western Plains Motel ($82/night)
- Badlands Inn ($130/night)
- Cedar Pass Lodge ($176/night)

####average price per day (no monthly changes):
83+130+176/3 = 129.67

### 3. Channel Islands: NO LODGING: Have to camp!

### 4. Glacier
- Red Lion Kalispell ($63/night) 
- Baymont by Wyndham ($65/night)
- Hilton Garden Inn Kalisplell ($79/night)

####average price per day:
63+65+79/3= 69

### 5. Grand Teton
- Snow King Resort & Condos ($99/night)
- Lexington @ Jackson Hole ($110/night)
- Anvil Hotel ($110/night)

####average price per day:
99+110+110/3 = 106.33

### 6. Redwood (only three listed)
- Redwood Coast Vacation Rentals ($55/night)
- Woodland Villa Cabins ($90/night)
- Elk Meadow Cabins ($159/night)

####average price per day:
55+90+159/3 = 101.33

### 7. Shenandoah
- quality inn skyline drive ($57/night)
- Days Inn ($70/night)
- Quality Inn ($75/night)

####average price per day:
57+70+75/3 = 67.33

### 8. Yellowstone
- Historic Madison ($50/night)
- Three Bear Lodge ($69/night)
- Absaroka Lodge ($85/night)

####average price per day:
50+69+85/3= 68

### 9. Yosemite
- Yosemite Sierra Inn ($74/night)
- Cedar Lodge ($79/night)
- Sierra Sky Ranch ($89/night)

####average price per day:
74+79+89/3= 80.67


### 10. Zion
- Parry Lodge ($69/night)
- Majestice View Lodge ($69/night)
- Driftwood Lodge ($79/night)

####average price per day:
69+69+79/3= 72.33




## 4. Car (price per trip)
- base mileage rate calculated from AAA national gas price as of March 2019 (https://gasprices.aaa.com/state-gas-price-averages) : **$2.45/gallon**
- average efficiency of a standard passenger car calculated from 2016 data (https://www.bts.gov/content/average-fuel-efficiency-us-light-duty-vehicles): **22 mpg** 
- distance calculated from UCSB (Goleta, CA) to the National Park using google maps
- TOTAL AUTO TRAVEL COST FORMULA:
$$ Cost = 2 * (distance(miles)/22mpg) *2.45/gallon $$

### Auto Distances and Round Trip Costs:
- SB--> Arches: 819 miles (**cost = 2 x (819/22 x 2.45) == $182.41 **)
- SB--> Badlands: 1,429 (**cost  = $318.28**)
- SB--> Channel Islands: 46 miles (**cost = $10.25**)
- SB--> Glacier: 1,436 (**cost = $319.84**)
- SB--> Grand Teton: 1,044 (**cost = 232.53 **)
- SB--> Redwood: 638 (**cost = $142.10**)
- SB--> Shenandoah: 2,692 (**cost = $599.58**)
- SB--> Yellowstone: 1,119 (**cost = $249.23**)
- SB--> Yosemite: 363 (**cost = 80.85**)
- SB--> Zion: 526 (**cost = 117.15**)



## 5. Plane (price per round-trip flight, plus extra)


## Calculation 1: round-trip flight to nearest airport
- total price is for one person 
- ** note: to make the data compilation easier, flights are from LAX to nearest major airport ** 
- predicted prices obtained from Google Flights
- base prices chosen from the lowest available and for a 4 day trip
- **no values available for February flights (I'm doing this data collection in March) --> so all February values are the same as the January value for that park
- ^cheaper to fly from SBA to fresno than LAX to fresno: prices have been reflected accordingly
- ^^Saint George Airport (SGU to fly in to Zion NP) is going to close from June-Sept 2019 so no flights or prices are available as of this data collection. based on the prices before & after this gap (about $212 for the cheapest flight), all values for June-Sept 2019 are assumed to be around 212.

### Plane Roundtrip costs:

### 1. Arches: LAX--> CNY 
- Jan: 223
- Feb**: 223
- Mar: 273
- Apr: 273
- May: 248
- June: 273
- July: 298
- Aug: 223
- Sep: 223
- Oct: 248
- Nov: 223
- Dec: 233


### 2. BadlandS: LAX--> RAP
- Jan: 412
- Feb**: 412 
- Mar: 428
- Apr: 393
- May: 412
- June: 370
- July: 300
- Aug: 300
- Sep: 412
- Oct: 412
- Nov: 412
- Dec: 412


### 3. SB--> Channel Islands: NO AIRPORT*, NO FLIGHTS
*Santa Rosa Island has a landing strip, but to avoid further complication and confusion it is assumed that the only way to make it to CINP is by boat

### 4. Glacier: LAX--> FCA  
- Jan: 216
- Feb**: 216 
- Mar: 285
- Apr: 224
- May: 224
- June: 194
- July: 207
- Aug: 207
- Sep: 224
- Oct: 224
- Nov: 224
- Dec: 224

### 5. Grand Teton: LAX--> JAC
- Jan: 317
- Feb**: 317 
- Mar: 294
- Apr: 294
- May: 277
- June: 317
- July: 317
- Aug: 302
- Sep: 302
- Oct: 317
- Nov: 322
- Dec: 317

### 6. Redwood: LAX--> ACV 
- Jan: 281
- Feb**: 281 
- Mar: 286
- Apr: 281
- May: 281
- June: 281
- July: 281
- Aug: 281
- Sep: 281
- Oct: 281
- Nov: 281
- Dec: 281

### 7. Shenandoah: LAX--> IAD 
- Jan: 287
- Feb**: 287 
- Mar: 287
- Apr: 258
- May: 217
- June: 266
- July: 272
- Aug: 267
- Sep: 267
- Oct: 287
- Nov: 287
- Dec: 287

### 8. Yellowstone: LAX--> JAC
- Jan: 317
- Feb**: 317 
- Mar: 294
- Apr: 294
- May: 277
- June: 317
- July: 317
- Aug: 302
- Sep: 302
- Oct: 317
- Nov: 322
- Dec: 317

### 9. Yosemite: SB^ --> FAT 
- Jan: 192
- Feb**: 192 
- Mar: 267
- Apr: 192
- May: 192
- June: 192
- July: 192
- Aug: 192
- Sep: 192
- Oct: 192
- Nov: 192
- Dec: 192

### 10. Zion: LAX --> SGU^^
- Jan: 212
- Feb**: 212 
- Mar: 212
- Apr: 212
- May: 212
- June: 212
- July: 212
- Aug: 212
- Sep: 212
- Oct: 212
- Nov: 212
- Dec: 212 



### Calculation 2: additional travel cost via car/bus/whatever to NP 
- **NOT** calculating rental car prices: using the gas mileage calculations as above

###Additional Mileage from:
- airport (CNY) --> arches: 14 miles (addnl $ = 3.12)
- airport (RAP) --> badlands: 54 miles (addnl $ = 12.03 )

- airport (FCA) --> glacier: 25 miles (addnl $ = 5.57)
- airport (JAC) --> grand teton: 4 miles (addnl $ = 0.89)
- airport (ACV) --> redwood: 26 miles (addnl $ = 5.79)
- airport (IAD) --> shenandoah: 56 miles (addnl $ = 12.47)
- airport (JAC) --> yellowstone: 71 miles (addnl $ = 15.81)
- airport (FAT) --> yosemite: 131 miles (addnl $ = 29.17)
- airport (SGU) --> zion: 45 miles (addnl $ = 10.02)



### FINAL CALCULATIONS: Plane Flight Formula:
where p is the number of people traveling:

$$ PlaneCost = p(TicketPrice) + (CarPrice) $$

## 6. Additional Fees?

- for ALL OTHER PARKS THAN CHANNEL ISLANDS: additional fee is the **EXTRA MILEAGE TRAVELED IF CHOSEN FLIGHT AS TRAVEL OPTION**
- for Channel Islands: need to include roundtrip boat price 

### Channel Islands: Overnight Boat Price (two adults):
- Anacapa: 79*2 = $158
- San Miguel: 147 * 2 = $294
- Santa Barbara: XX (closed for 2019)
- Santa Cruz: 79 *2 = $158
- Santa Rosa: 114 * 2 = $228

**average price for boating (from four islands) is = $209.50 **




## Travel Cost Formula

where x is the number of days staying at the NP, 

$$TRAVEL COST = (Park Entrance) + [CampFee*x]||[HotelPrice*x] + [CarRound]||[PlaneRound] + AddnlFee$$